name: online-data-store
volumes:
  block-persist-project15:
services:
  
  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - mnt/block/saved_videos:mnt/openvid/inference_videos
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi
	rclone copy mnt/openvid/inference_videos chi_tacc:$RCLONE_CONTAINER \
        --progress \
        --transfers=32 \
        --checkers=16 \
        --multi-thread-streams=4 \
        --fast-list

        echo "Listing directories in container after load stage:"
        rclone lsd chi_tacc:$RCLONE_CONTAINER
